### ISSUE TITLE
Excel row- & col-span

### ISSUE THREAD

**Issue by rdmueller** [uniqueck/asciidoctorj-office-extension#1]
I just stumbled upon this project and I have to say I think it is great and quite helpful!
I will reference it from docToolchain asap.

I've also seen that you noted down as open issues the implementation of row- and col-span for excel.
Have you checked out the code in docToolchain for the `exportExcel`-Task?

https://github.com/docToolchain/docToolchain/blob/master/scripts/exportExcel.gradle

It is capable of handling row- and col-spans, alignments, col-width and background colors.

**Comment by uniqueck** [comment]
Hi @rdmueller, nice to hear from you. 
I discussed this extensions and year ago with Gernot Starke and mentioned that i referenced it from docToolChain [issue](https://github.com/docToolchain/docToolchain/issues/231#issuecomment-539878575) to give it a try, but i got no reply. He told me than, that you currently very busy, so i'm happy to hear from you. I can implement the alignment stuff, that is not a big deal. It is nice to hear that you will reference this extension from doctoolchain. This extension is inspired based on the stuff from doctoolchain, but im not a big fan from gradle, so i implement an extension independet from the build tool.

**Comment by rdmueller** [comment]
btw: gradl eis currently my main pain with docToolchain. It makes docToolchain slow. So I try to avoid it in the future. And that's where your extension will be quite useful.

**Comment by uniqueck** [comment]
Hi Ralf, that sounds great. 
Should i help you to extract the asciidoctor code as extensions, so we can easily migrate to a newer asciidoctor version? Maybe it helps if i an member of the doctoolchain organization?

**Comment by rdmueller** [comment]
Hi Constantin,
indeed, I could need some help for the next generation (ng) version 2.0 for docToolchain.
but first, I guess I need to write some more docs to enable people to help and find a good way to remove gradle in the first place.

So, I have just started a discussion where I ask for help - I would be more than happy if you where the first one to answer :-)

https://github.com/docToolchain/docToolchain/discussions/607

**Comment by crea-doo** [comment]
I've added a PR (https://github.com/uniqueck/asciidoctorj-office-extension/pull/5) which implements the proposed changes.
As proposed the blueprint for this is the implementation at https://github.com/docToolchain/docToolchain/blob/master/scripts/exportExcel.gradle.
Additionally support for hyperlinks in cells is implemented.
