### ISSUE TITLE
Gradle?

### ISSUE THREAD

**Issue by rdmueller** [uniqueck/asciidoctorj-office-extension#2]
Have you already tried to get this up and running with gradle?
I ask, because we currently to to integrate this into docToolchain. And it seems a simple reference to your lib isn't enough...

**Comment by uniqueck** [comment]
Hi @rdmueller, do you have a repository where i can try it? This extension use the SPI mechanism so if it is present on the classpath it will auto registered.

**Comment by rdmueller** [comment]
here is the place we worked on integrating your plugin:
https://github.com/mattes3/docToolchain/tree/issue-556

don't know if this helps, because the project has quite some size.

**Comment by uniqueck** [comment]
Hi @rdmueller,

i created a little working example based on gradle. I hope it helps. Have a look at [https://github.com/uniqueck/asciidoctorj-extension-gradle-example](https://github.com/uniqueck/asciidoctorj-extension-gradle-example). 
I also leave a comment on the issue you mentioned.

**Comment by rdmueller** [comment]
perfect. thanx!
